### PR TITLE
[WIP] Web removal

### PR DESCRIPTION
**Pull request by mcdonnelldean**
Removal of seneca-web as a default plugin. Please do not merge until WIP is removed as we are cross checking with other plugins.

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@rjrodger This will need a little thought. It breaks Transport.

**Comment by rjrodger** [comment]
that's a strange dependency that should not exist...

**Comment by mcdonnelldean** [comment]
Yeah that was my thinking, especially reading through transport. I'll find and unlink whatever it is.

Kindest Regards,

Dean

**Comment by mihaidma** [comment]
@mcdonnelldean LGTM

**Pull request merged**
