### PR TITLE
replaced logrouter with seneca-log-filter

### PR DESCRIPTION
**Pull request by mihaidma**

### CODE REVIEW

**Comment by dgonzalez** [comment]
Neat. LGTM.

**Comment by mcdonnelldean** [comment]
@mihaidma Magic! Let me know if your happy for merge

**Comment by mihaidma** [comment]
@mcdonnelldean I just realized the log filter needs aliases to be set. I'll add them.

**Comment by mcdonnelldean** [comment]
@mihaidma 👍

**Comment by mihaidma** [comment]
@dgonzalez could you please review the logging.js file? is this what you were thinking it should look like?

@mcdonnelldean the log filter is fully integrated, works. In logging.js you can see all the aliases from options and command line. I think they are inconsistent, we should have both command line and options support the same aliases and these should be: `silent`, `all` and maybe `test` and `standard`.

**Comment by mcdonnelldean** [comment]
Yes lets make the alias match whatever they we're. Otherwise it's a major version change. Also these should be in log-filter by default.

They can be switched off but thats where they should live since they are our defaults.

Otherwise we haven't fully solved the issue.

Kindest Regards,

Dean

On 12 Sep 2016, at 23:27, Mihai Dima <notifications@github.com<mailto:notifications@github.com>> wrote:


@dgonzalez<https://github.com/dgonzalez> could you please review the logging.js file? is this what you were thinking it should look like?

@mcdonnelldean<https://github.com/mcdonnelldean> the log filter is fully integrated, works. In logging.js you can see all the aliases from options and command line. I think they are inconsistent, we should have both command line and options support the same aliases and these should be: silent, all and maybe test and standard.

-

**Comment by dgonzalez** [comment]
Yup. It makes sense to me. seneca-log-filter on my opinion should be alias agnostic (aside from the levels that are pretty standard) and then seneca inject the knowledge of what 'test' (or all or any other alias) is. This way the file logging.js is quite clear to me (not sure for someone who didn't have exposure to it before).

**Comment by dgonzalez** [comment]
Now the question is... do we want everyone using seneca-log-filter knowing about the seneca aliases by default?

**Comment by mcdonnelldean** [comment]
Yes,

Those aliases are cannon as such. You shouldn't need to reimplement them. You can not use them but by default they should be part of the filter.

If they aren't every logger will have to reimplement them, making the whole idea of taking it out in the first place pointless

Kindest Regards,

Dean

On 13 Sep 2016, at 08:48, David <notifications@github.com<mailto:notifications@github.com>> wrote:


Now the question is... do we want everyone using seneca-log-filter knowing about the seneca aliases by default?

-

**Comment by mihaidma** [comment]
@mcdonnelldean this can be merged.

A unified alias system seems ok to me. We can have seneca aliases hardcoded in the filter.
One more issue I see: the filter should be able to process both `{log: { level: 'error+' }}` and `{log: 'test}'` log options formats.

**Comment by mcdonnelldean** [comment]
@mihaidma @dgonzalez this is fine for now but can we get an issue open on seneca to support top level aliases? `log:'silent'`, `log:'magic'` and `log:'yehaw'` should all be allowable as aliases that generate a valid structure. (assuming something understands the alias and can process it). By default it should support `all`, `silent`, and `test` at the root.

@mihaidma My assumption is `error+` is supported in that format?

**Comment by mihaidma** [comment]
@mcdonnelldean 
These are the root aliases log levels:
- `all` sets log level to `debug+`,
- `silent` sets log level to `none`,
- `test` represents the `error+` level

and are used as:
```
var seneca = Seneca({
  log: 'test'
})
```
error+ is a supported log level format at this moment.

An alias level can be set in the options also at this moment, it is not an issue. @dgonzalez is updating the log-filter to understand {log: 'alias'} formats.

**Comment by mcdonnelldean** [comment]
Perfetto!

Kindest Regards,

Dean

On 13 Sep 2016, at 10:29, Mihai Dima <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcdonnelldean<https://github.com/mcdonnelldean>
These are the root aliases log levels:

  *   all sets log level to debug+,
  *   silent sets log level to none,
  *   test represents the error+ level

and are used as:

var seneca = Seneca({
  log: 'test'
})


error+ is a supported log level format at this moment.

An alias level can be set in the options also at this moment, it is not an issue. @dgonzalez<https://github.com/dgonzalez> is updating the log-filter to understand {log: 'alias'} formats.

-

**Comment by mihaidma** [comment]
@mcdonnelldean integrated the latest log filter, PR work finished

**Comment by mcdonnelldean** [comment]
@mihaidma Good work! This is nice.

**Pull request merged**
