### PR TITLE
fix rjrodger/seneca#185

### PR DESCRIPTION
**Pull request by maxired**
Hi,

This fix the fact that arrays Arrays can't be used as default value.

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
Awesome, looks good, @geek can you give a LGTM?

**Comment by geek** [comment]
LGTM

Is there any updates we need to do to the documentation?

**Comment by maxired** [comment]
I will check that tomorrow, but I don't think so.

**Comment by maxired** [comment]
@geek, I checked in the repo and seneca.org and didn't find documentations regarding default$ parameter for act.

**Comment by mcdonnelldean** [comment]
@maxired Should have have something written about this?

**Comment by maxired** [comment]
@mcdonnelldean , I am afraid that yes. but maybe it exists and I just missed it.

**Comment by mcdonnelldean** [comment]
@maxired I'd say it's most likely it doesn't exist :dancer: 

Ok can you pop an issue on senecajs.org with the basis of what it does and how we need to document it. We can then get someone to work with @orlacoding do get some documentation on it.

**Comment by geek** [comment]
Closing in favor of https://github.com/senecajs/seneca/pull/210 which is against the 0.8 branch

**Pull request closed without merging**
