### PR TITLE
Updating actmeta.descdata

### PR DESCRIPTION
**Pull request by brycereynolds**
I've left a ticket explaining this request.

https://github.com/senecajs/seneca/issues/360

### CODE REVIEW

**Comment by geek** [comment]
@brycereynolds looks good, can you also add a test for this, to keep us from regressing.

**Comment by brycereynolds** [comment]
Yup I couldn't exactly tell the best test file to put that in. Any advice?

**Comment by geek** [comment]
@brycereynolds you can put it in the seneca.test.js file, or really any that have `.test.js`

**Comment by geek** [comment]
@brycereynolds closing for now, please reopen when you have added a test

**Pull request closed without merging**
