### PR TITLE
seneca.fail - allow the boolean first arg to trigger the error throw

### PR DESCRIPTION
**Pull request by lilsweetcaligula**
#781 

Ave, guys. Thank you for your hard work on Seneca!

This PR implements the optional `cond` argument, as requested in #781, that only causes the method to throw if it's `true`.

Q: Should the automatically updated `./test/coverage.html` file be committed as well?
Q: Where may I update documentation? The `package.json` file does not seem to have the `annotate` script as suggested by the readme file.

### CODE REVIEW

**Comment by lilsweetcaligula** [comment]
Just a note - I am a bit concerned that, in some rare cases client code may pass extraneous arguments to the `seneca.fail` method, e.g.:
```
const args = ['code', { foo: 'bar' }, 1]
//
// 10 lines below

seneca.fail(...args)
```

Such client code will break if we "overload" the method, based on the number of arguments.

**Comment by rjrodger** [comment]
Thank you - this looks good!

**Comment by rjrodger** [comment]
Please also commit test/coverage.html - we are experimenting with committing this as standard as it feel useful

**Comment by rjrodger** [comment]
documentation: `fail` is missing from this page: https://github.com/senecajs/senecajs.org/blob/master/src/pages/api/index.html.ejs#L119
https://senecajs.org/api/#methods

**Comment by lilsweetcaligula** [comment]
@rjrodger Thank you for taking the time to take a look!

Would you like me to create the issues?

> Please also commit test/coverage.html - we are experimenting with committing this as standard as it feel useful


> documentation: fail is missing from this page: https://github.com/senecajs/senecajs.org/blob/master/src/pages/api/index.html.ejs#L119
https://senecajs.org/api/#methods

**Comment by rjrodger** [comment]
yes please :)

**Comment by lilsweetcaligula** [comment]
@rjrodger 
Please take a look when you have the time:
https://github.com/senecajs/seneca/issues/860
https://github.com/senecajs/seneca/issues/859

**Pull request merged**
