### PR TITLE
chore: upgrade npm

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by rjrodger** [comment]
are these equivalent?

**Comment by DanielRuf** [comment]
> are these equivalent?

Which "these"?

**Comment by DanielRuf** [comment]
> > are these equivalent?
> 
> Which "these"?

It first upgrades npm and then always uses `npm ci`.

**Comment by rjrodger** [comment]
`NODE_VERSION=$(node -v); if [ ${NODE_VERSION:1:2} -ge 10 ]; then npm i -g npm@6; npm ci; else npm install; fi` 
vs
`npm i -g npm@latest; npm ci`

do they give the same behaviour for 4 <= node <= 10? if so, great :)

**Comment by DanielRuf** [comment]
> do they give the same behaviour for 4 <= node <= 10? if so, great :)

Yes, they both use `npm ci`, the node version does not directly matter but the npm version.

**Comment by rjrodger** [comment]
merged - thanks!

**Comment by rjrodger** [comment]
nope! https://travis-ci.org/senecajs/seneca/jobs/405041001
will have to revert i'm afraid

**Comment by DanielRuf** [comment]
Node 6 is needed at least, Node 4 reached its EOL a few months ago.

**Comment by DanielRuf** [comment]
Well, then let's revert this one and keep this in mind for the future. Or switch to yarn which should be faster.

**Comment by DanielRuf** [comment]
But why wasn't this triggered on CI before (in this PR)?

**Pull request merged**
