### PR TITLE
fix plugin definition error in a 0.9.2

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
*has commit name says :D*

Fixed error:
```
Seneca Fatal Error
==================

Message: internals.Error is not a function

Code: undefined

Details: undefined

Stack:
    at define_plugin (/Users/abecchis/git-adot/-seneca-forks/seneca-cron/node_modules/seneca/lib/plugins.js:295:21)
    at Seneca.api_register [as register] (/Users/abecchis/git-adot/-seneca-forks/seneca-cron/node_modules/seneca/lib/plugins.js:66:14)
    at Seneca.api_use [as use] (/Users/abecchis/git-adot/-seneca-forks/seneca-cron/node_modules/seneca/seneca.js:971:10)
    at initSeneca (/Users/abecchis/git-adot/-seneca-forks/seneca-cron/test/cron.test.js:28:8)
    at Immediate._onImmediate (/Users/abecchis/git-adot/-seneca-forks/seneca-cron/node_modules/lab/lib/runner.js:467:17)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Instance: Seneca/0.9.1/4gzvk7qjnhrf/1449742179085/15463/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at Seneca.api_register [as register] (/Users/abecchis/git-adot/-seneca-forks/seneca-cron/node_modules/seneca/lib/plugins.js:69:23)

```

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Node build error comes since last master commit: : https://travis-ci.org/senecajs/seneca/builds

failing test: `'act during plugin initialization is deprecated'` and `calling act from init actor is deprecated`

**Comment by geek** [comment]
Looks good, can you also add a test for this bug

**Comment by AdrieanKhisbe** [comment]
Here is associated test :)

**Comment by geek** [comment]
@AdrieanKhisbe thank you!

**Comment by AdrieanKhisbe** [comment]
:smiley:

**Pull request merged**
