### PR TITLE
Lint seneca.js and lib folder

### PR DESCRIPTION
**Pull request by maxired**
Hi,

Here is a PR regarding lintage of seneca.js and lib folder, in order to conform to [js-standard-style](https://github.com/feross/standard)
Lintage of tests will come in a separate PR.

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@maxired Nice!!

I just want to get a quick :+1: form @rjrodger and @geek before accepting but it all LGTM :D

**Comment by maxired** [comment]
@geek , I am currently rebasing it on top of master

**Comment by geek** [comment]
@maxired ping when you are ready

**Comment by maxired** [comment]
@geek, ping. 

The green light says that you can merge ;)

**Comment by geek** [comment]
@maxired thanks for the work here.  I used this PR to help with #207 and #208.  A couple of the lint rules changed around if/else so I created separate PRs.  Closing this as the lint work is all done (with the exception of seneca.js, which I am working on now).

**Pull request closed without merging**
