### PR TITLE
Error handling and bootstrap refactor

### PR DESCRIPTION
**Pull request by mcollina**
See the discussion in https://github.com/senecajs/seneca/issues/398.

Seneca-transport needs the same treatment, coming soon.

If we decide to merge this, we might want to do a 3.x prerelease, to start checking all the applications and plugins.

cc @pelger @davidmarkclements @mcdonnelldean @AdrianRossouw @rjrodger.

### CODE REVIEW

**Comment by mcollina** [comment]
I'm not convinced by `seneca.die()`, not sure if it has to go as well.

**Comment by mcollina** [comment]
Also, I have not touched the timeout.

**Comment by mcollina** [comment]
I'm currently blocked on https://github.com/senecajs/seneca-transport/issues/88.

**Comment by mcdonnelldean** [comment]
@mcollina I'll review and unblock you. Agree on the pre-release. Let's discuss that tomorrow. Nodezoo will have a reasonable test suite soon that we can run this through (along with manual testing).

**Comment by mcdonnelldean** [comment]
@mcollina master of seneca-transport should now pass correctly.

**Comment by mcdonnelldean** [comment]
@mcollina Just to note, don't change the tests, let the fail when you PR. I want to ensure we know what breaks so we can understand the impact of the change to existing users.

**Comment by mcollina** [comment]
So, where is the 30 second timeout for each act? Is it still in or did it go?

I did the same treatment to seneca-transport: https://github.com/senecajs/seneca-transport/pull/94

**Comment by mcollina** [comment]
How would you like to proceed? I think we should do a `seneca@next` release and test this on nodezoo. Ideally, there should be no breakage.

**Comment by mcdonnelldean** [comment]
@mcollina Timeouts are handled by the gate executor. Yeah so the next stage is get a preview release out to play with. We need to be super careful on backwards compat here because errors. So here's what we do.

1. Create a new branch called next and push your work to there.
2. Talk @naomifeehanmoran through releasing a preview of this branch on npm
3. Have @mihaidma wire up the preview to his existing test suite

What this will give us, by convention is a place to test v.next features without stopping patches / minors going to master. @mihaidma has an almost fully automated test suite, it makes perfect sense to wire in a v.next for times where changes could be really bad.

This will leave us with a next branch, and release which will need to be maintained but it is a small price to pay for full access to the automation suite for testing. @mcollina We are doing the same changes to NodeZoo so we will eventually have two Org sized test suites to run against.

Do not merge to master! We need to keep master free for bugs and patching until next stablizes. Basically, if it's likely to break do it in next. If it's a fix do it in master and merge to next. Each time next stablises and is proved compatible we can merge to master.

**Comment by mcollina** [comment]
There is one more thing to do, and it is in the gate-executor.

**Comment by mcdonnelldean** [comment]
👍

**Comment by mcollina** [comment]
I've reached a point with this, it is already massive so it's better this being reviewed/test before I continue.

There is really a lot to explain, I will try my best but make questions and review.

The problem with error handling and why it is so hard to debug seneca application is that *every `act()` is wrapped within a `setImmediate` and everything is wrapped in a try-catch to help reconstructing issues*. Removing all the try-catches will not be enough to solve #398, as we need a simple way to track down errors and support easy stack traces. Unneeded asynchronicity is damaging the user experience.

I have also found out that in several occasions the "normal flow" of acts might be altered by the `gate-executor`, in a process called "gating" #411. Again, everything that modified the flow of messages makes debugging harder, and the flow of async calls should stay in the same order. However, "gating" is needed to safely boot a seneca application.

So I implemented several changes:

1. removed all error handling and try catch, no more `seneca.error` or `seneca.options({ errhandler: fn })`, 2. remove all `process` events handling, `seneca.die` and `fatal$`
3. removed `gate-executor`, and replaced with a simple boot queue built upon [fastq](http://npm.im/fastq).
4. removed `gate$`  and `ungate$` in actions
5. anything that called `seneca.die` now does a `seneca.emit('error', err)` (we might even alias `die` to emit('error')`, as backward compat).

The bootstrap process is as follow:

0. the user issue a series of `use`, `add`,  `act` and  `ready`  in the 'starting' tick (when we instantiate the seneca instance)
1. we execute every method called in step 1, one at a time and in series, starting at the end of tick
2. all `act()` issued after the first "locked" tick are executed as normal
3. when the current method call defined in step 1 is finished, the next one is executed
4. `seneca.client()` is wrapped in a `seneca.ready` otherwise it cannot work in this bootstrap process

The above as the exact same effect of  `gate$` and `ungate$`, but without the need of gating all the messages after the boot has completed.

**Comment by mcdonnelldean** [comment]
@mcollina Epic stuff.

/All, before everyone gets excitable over this PR please remember it is an experiment right now. Phase one, do the work, is now done. Phase two, what did we actually break is next. I'll be working through the code and testing it against various systems to figure out where we are here.

I'll be working with some community members on this too, there is a lot of interest from the community in error handling and inconsistencies in flow so particular project leads have signaled interest in testing to see if this breaks a little or a lot for them.

**Comment by rjrodger** [comment]
@mcollina lots to review - let me make some comments over the next few days :)

Asynchronous actions: actions may or may not execute remotely - you just don't know. Up to 0.3 local actions were actually synchronous, but this caused issues when you moved to a distributed configuration. So all actions need to be async, to ensure that you handle them correctly in client code, and don't rely on behaviour that will change. /cc @pelger

**Comment by rjrodger** [comment]
@mcollina 

bootstrapping: actually there is no bootstrapping as such - you can load plugins at any time, and add actions at any time. seneca.ready should be called every time the current batch of gated actions finishes. Plugin init actions are gated to support. All gating does is prevent actions submitted after the plugin init starts, but before it completes, from executing.

**Comment by rjrodger** [comment]
@mcollina 

Try-catch should not be part of the logic flow, so you should be able to remove all these without removing anything else - can you confirm/deny this assumption? :)

**Comment by rjrodger** [comment]
@mcollina bear in mind the backwards compatibility requirement for each major release: the only allowed change is one extra line of code to add legacy functonality via a plugin. For 2.0 this was

```
seneca()
  .use('entity')
```

3.0 will need to work the same way

**Comment by mcdonnelldean** [comment]
Oops, so this being in a milestone was my mistake, @rjrodger I accidentally had this in 3.0 (PR's shouldn't have milestones anyway, their related issues should).

**Comment by mcollina** [comment]
@rjrodger:
> Try-catch should not be part of the logic flow, so you should be able to remove all these without removing anything else - can you confirm/deny this assumption?

Denied, I tried and failed badly. I could not get a working Seneca version where the stacktrace contained enough information to reconstruct where and Error is happening, without a global error handler and without the try catches. All of these are connected to each other. Let me explain my reasoning.

Error handling is a key part of the gate-executor, which wraps every call in a setImmediate and a try-catch, and then it routes all the thrown exception to the seneca error handler. The error reconstruction mechanism is done via the "callpoint" which is completely optional but useful in development, and it is used to reconstruct the stacktrace in development.

To complicate things further, the gate-executor can alter the order of acts (all `gate$: true` actions are prioritized before all the others), making things even harder to debug.

Let's assume in file `a.js` at line 42, you call microservice B via an `act()`. In order to let a developer know that a specific `act` in a.js:42 caused B to explode, you cannot execute this inside a `setImmediate` without a try-catch. _Just_ removing the try-catch and keeping the `setImmediate` will make error handling worse.

Removing `setImmediate` is not possible, as all without it all the plugin loading mechanism and chainable  breaks, and this is the reason that lead to 'gating' in the first place. In order to be able to remove `setImmediate` for the normal "operation", I had to come up with a mechanism that is functionally equivalent to gating in the chainable api form.

I rethinked the way we load plugins, what I call as "bootstrapping", as it is explained in my above comment. I'll copy-paste here for ease of discussion:

0. the user issue a series of `use`, `add`,  `act` and  `ready`  in the 'starting' tick (when we instantiate the seneca instance)
1. we execute every method called in step 1, one at a time and in series, starting at the end of tick
2. all `act()` issued after the first "locked" tick are executed as normal
3. when the current method call defined in step 1 is finished, the next one is executed
4. `seneca.client()` is wrapped in a `seneca.ready` otherwise it cannot work in this bootstrap process

This pattern supports:

```js
seneca()
  .use('entity')
```

without any issue. The only catch is that any `seneca.make$`  call now needs to be executed _after_ ready (see https://github.com/senecajs/seneca/pull/402/files#diff-a14c281de7a948affaaa2411c489dcbbR47). But we can provide a shim for backward compatibility if needed.

What it does not support, it is loading plugins after the system is loaded, probably during a command received from a remote service. This is a really bad idea in the first place (node is not OTP), and we should not support it in the first place (it is also against all the node best practices). To be true, it is supported in the sense that the plugin will load, but the seneca instance will not be "gated" and all the other (concurrent) acts will be executed in parallel.

On the async matter, we might want to have the act `callback` to be always called asynchronously, but that's another story. I am against that for performance reason, but I think it might be good for backward compatibility, if calling act synchronously causes issues.

So, my conclusion is that it is impossible to fix error handling without touching the way seneca executes acts and load plugins. It is an extremely core thing, with an high chance of causing breakage.

If you folks are ok with that, I will update this with #414, but let's discuss it there.

**Comment by mcollina** [comment]
To handle some of the functionality of the current "global" error handling, we can have something like https://github.com/roylines/hapi-graceful-pm2, that in the event of error it shuts everything down.

**Comment by mcdonnelldean** [comment]
As agreed with @mcollina we are going to close this for now while all of the clean up work happens. We won't delete it as there are some things in the PR that need to be added eventually but the worry is somebody accidentally merges... then we have a bad time.

**Pull request closed without merging**
