### PR TITLE
Add Golden Circle testing

### PR DESCRIPTION
**Pull request by mihaidma**
automatically run seneca against some of the golden circle plugins

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@mihaidma Lets add Node 6 into this PR too since it is all related to having a full test suite.

**Comment by mcdonnelldean** [comment]
@mihaidma Go ahead and remove 6 on this for now. We can investigate that later in the month.

**Comment by mihaidma** [comment]
The task is done.
@mcdonnelldean seems also that everything passes.
I'll fix next the transport tests.

**Comment by mcdonnelldean** [comment]
Awesome! @StarpTech now this is in a version will go out this afternoon. Appologies for the delay but this was vital work that needed time to complete.

**Pull request merged**
